name: weatherAppMobile
description: Weather App Project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.2
  simple_animations: ^1.3.4
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2

flutter:

  uses-material-design: true
